services:
    radius.compte:
        class: LUCIE\RadiusBundle\Compte\LUCompte
        arguments: [ "@doctrine.orm.entity_manager", "@form.factory", "@service_container" ]
        tags:
            - { name: form.type }

#    lucie_radius.example:
#        class: LUCIE\RadiusBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
