services:
    radius.compte:
        class: LUCIE\RadiusBundle\Compte\LUCompte
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]

#    lucie_radius.example:
#        class: LUCIE\RadiusBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
