LUCIE\RadiusBundle\Entity\Radusergroup:
    type: entity
    table: null
    repositoryClass: LUCIE\RadiusBundle\Repository\RadusergroupRepository
    id:
        username:
            type: string
            id: true
        groupname:
	    type: string
	    id: true        
    fields:
        priority:
            type: integer
    lifecycleCallbacks: {  }
