LUCIE\RadiusBundle\Entity\Userinfo:
    type: entity
    table: null
    repositoryClass: LUCIE\RadiusBundle\Repository\UserinfoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '128'
            nullable: true
        firstname:
            type: string
            length: '200'
            nullable: true
        lastname:
            type: string
            length: '200'
            nullable: true
        email:
            type: string
            length: '200'
            nullable: true
        department:
            type: string
            length: '200'
            nullable: true
        company:
            type: string
            length: '200'
            nullable: true
        workphone:
            type: string
            length: '200'
            nullable: true
        homephone:
            type: string
            length: '200'
            nullable: true
        mobilephone:
            type: string
            length: '200'
            nullable: true
        address:
            type: string
            length: '200'
            nullable: true
        city:
            type: string
            length: '200'
            nullable: true
        state:
            type: string
            length: '200'
            nullable: true
        country:
            type: string
            length: '100'
            nullable: true
        zip:
            type: string
            length: '200'
            nullable: true
        notes:
            type: string
            length: '200'
            nullable: true
        changeuserinfo:
            type: string
            length: '128'
            nullable: true
        portalloginpassword:
            type: string
            length: '128'
            nullable: true
        enableportallogin:
            type: integer
            nullable: true
        creationdate:
            type: datetime
            nullable: true
        creationby:
            type: string
            length: '128'
            nullable: true
        updatedate:
            type: datetime
            nullable: true
        updateby:
            type: string
            length: '128'
            nullable: true
    lifecycleCallbacks: {  }
