<?php

namespace LUCIE\RadiusBundle\Repository;

/**
 * RadcheckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadcheckRepository extends \Doctrine\ORM\EntityRepository
{
}
