<?php

namespace LUCIE\RadiusBundle\Repository;

/**
 * RadgroupcheckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadgroupcheckRepository extends \Doctrine\ORM\EntityRepository
{
}
