<?php

namespace LUCIE\RadiusBundle\Repository;

/**
 * RadgroupreplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadgroupreplyRepository extends \Doctrine\ORM\EntityRepository
{
}
