<?php

namespace LUCIE\RadiusBundle\Repository;

/**
 * RadreplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadreplyRepository extends \Doctrine\ORM\EntityRepository
{
}
