<?php

namespace LUCIE\RadiusBundle\Repository;

/**
 * RadusergroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadusergroupRepository extends \Doctrine\ORM\EntityRepository
{
}
