<?php

namespace LUCIE\RadiusBundle\Repository;

/**
 * UserbillinfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserbillinfoRepository extends \Doctrine\ORM\EntityRepository
{
}
